input {
  tcp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  if [message] {
    mutate {
      add_field => { "workshop" => "true" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "workshop-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}